### ISSUE TITLE
[FEAT]: 채팅방뷰의 기본 구조를 구현합니다.

### ISSUE THREAD

**Issue by yudonlee** [DeveloperAcademy-POSTECH/MacC-Team-Vegeting#106]
### 구현 Task List
채팅방 UI를 구현합니다. 전체 Task를 한번에 하기는 불가능 이기 때문에 Task를 나누어보았습니다.(Issue 또한 분리할 예정입니다.)
- 1. 내가 보낸 메시지와, 남이 보낸 메시지가 동일하게 사용되는 1번 타입을 먼저 만듭니다.
- 2. sender가 나인지 아닌지에 따라서 메세지가 왼쪽에서 시작될지, 오른쪽에서 시작될지 결정하도록 구현합니다. 
- 3. 해당 구현이 끝나면 2번 타입을 구현하게 됩니다. 
- 4. 3번의 연장선에서, 프로필을 표시해야 하는 row인지 아닌지를 결정하는 로직을 구현합니다. 
- 5. 기본적으로 구현된 채팅방 UI으로 채팅을수신합니다. 
- 6. 텍스트는 최대 3줄까지 보여주며 그 이상은 사이즈가 커지지 않습니다. 
- 7. 이때 메세지 입력을 받는 TextField는 키보드 위에 붙어 있으며, 그에따라서 채팅방의 Scroll또한 올라가야 합니다.(키보드가 채팅창을 가리는 만큼 채팅방의 높이또한 올려주어야 합니다.) 
- 8. 마지막으로 남은 날짜를 supplementaryView에 표시합니다. 
- 9. 해당 메세지가 그날의 최신 메시지임을 알려주는 로직을 구현합니다. 
### 채팅방 UI에서 Cell의 2가지 타입
1. 채팅한 내용과 시간이 같이 있는 경우 
<img width="452" alt="image" src="https://user-images.githubusercontent.com/39371835/201335527-1843339c-b7bb-48d3-98a2-7d9d70a96924.png">
2. 채팅한 내용, 프로필, 시간이 있는 경우
<img width="454" alt="image" src="https://user-images.githubusercontent.com/39371835/201335701-5681e288-0494-484d-8572-8a39684d5022.png">

### CollectionView로 구현하는 이유 
TableView와 CollectionView는 Grid가 한줄에 여러개가 아닌 이상, 쓰임에서 크게 차이가 안난다고 생각했고 그리하여 처음에는 TableView로 구현하고자 하였습니다. 하지만 그 결정을 철회한 이유가 있습니다.
1. Supplementary View의 부재 
SupplementaryView는 TableView의 HeaderView, FooterView와 비슷한 기능을 한다고 생각할 수 있지만, 사실 전혀 다릅니다. 
HeaderView는 메세지에 대해서 날짜벼롤 Section을 강제로 만들고 그에 따른 rowItem 들도 구현하는 로직이 필요합니다. 
하지만 supplementaryView는 해당 row가 조건을 충족할 경우 supplementaryView를 제공하면 되기에 비교적 더욱 간단합니다. 
![image](https://user-images.githubusercontent.com/39371835/201370598-a6f51f0f-3f6b-4ac2-b44d-1f1bbb0fcdc9.png)

## 📝  todo
- [x] 1번 타입의 채팅 메세지 CollectionView Cell 구현(남이 보낸 채팅 기준)
- [x] 내가 보낸 채팅을 기준으로 UI 구현
- [x] cell별 margin 적용
