### ISSUE TITLE
[FEAT]: 파이어베이스에서 모든 클럽, 가입한 클럽을 불러와 띄워주기

### ISSUE THREAD

**Issue by kelly1422** [DeveloperAcademy-POSTECH/MacC-Team-Vegeting#107]
## 💡 Issue
저장되어 있는 모든 클럽 내용을 파베에서 불러와 메인뷰 UI에 맞춰 띄워줍니다. 
내가 가입한 클럽만 메인뷰와 같은 형식으로 띄워줍니다. 

## 📝  todo
- [x] 파베 clubs document를 불러와 Club 객체로 변환해주는 함수를 호출해 메인뷰의 클럽리스트에 저장하고 UI 업데이트
- [x] 파베 clubs document를 불러와 Club 객체로 변경후 participants에 currentUser가 있는 클럽만 배열에 저장해 반환하는 api 작성
- [x] MyPage의 가입한 모임 버튼을 클릭하면 위에 작성한 함수를 이용해 UI 업데이트
