### ISSUE TITLE
[FEAT]: supplementaryView를 통해 날짜 표시

### ISSUE THREAD

**Issue by yudonlee** [DeveloperAcademy-POSTECH/MacC-Team-Vegeting#114]
## 💡 Issue

- #106 4번Task
4번 Task는 supplementaryView를 구현하여 해당 메시지가 전송된 날짜를 기준으로 가장 빨리 보낸 메세지라면 날짜를 표시합니다.     

| 이전작업 | 추가될 작업 |
| ---------- | ---------- |
| <img width="402" alt="image" src="https://user-images.githubusercontent.com/39371835/201504909-f9afbd93-ef62-404b-9161-796a41e2b25b.png"> | <img width="601" alt="image" src="https://user-images.githubusercontent.com/39371835/201512569-ca32c344-d597-4555-905d-f3e2f6f4e33f.png"> |

## 📝  todo
- [ ] supplementaryView를 UICompositionalLayout으로 크기 지정
- [ ] supplementaryView의 view layout 그리기 
- [ ] supplementaryView와 collectionView 연결하기

## 참고한 코드 출처
- []()
