### ISSUE TITLE
[FEAT]: 채팅 데이터 서버로부터 수신

### ISSUE THREAD

**Issue by yudonlee** [DeveloperAcademy-POSTECH/MacC-Team-Vegeting#117]
## 💡 Issue

- #106 5번째 Task
- 채팅방 ViewModel을 생성하고, 서버와 View모델을 연결한다
### 전체 서버 및 ViewModel 구조도
<img width="708" alt="image" src="https://user-images.githubusercontent.com/39371835/201518403-d83c7de5-67c2-48f8-b1ae-66b012dc9a3c.png">

- ViewModel이 VC로부터 감지하고 있는 UI Event는 viewWillAppear과 sendButton Tapped이다.
- ViewModel이 VC에 전달하는 값은 ServerChangedData와 localChatDataChange이다. 
### Input(UIEvent)
1. ViewWillAppear
- ViewWillAppear이 감지될 시, 서버로부터 데이터를 불러와서 ServerData를 VC에 전달한다.
- VC는 해당 데이터를 통해 collectionView를 reload한다. 
2. SendButtonTapped
- 메세지 전송버튼을 통해서 Text 데이터가 ViewModel에 전달된다.
- 전달된 ViewModel에서는 일단 local값들의 변화를 채팅방에 송신한다.
- 해당 local 값들을 통해서 채팅방이 reload된다. 
- 그것과 동시에 서버에 해당 메세지를 전송한다. 그 후, ServerData가 변화하게 되면, 해당 값을 ViewModel이 수신한다.
- 서버로부터 수신된 정보들을 가지고 다시한번 VC에 채팅정보를 송신한다. 

## 📝  todo
- [ ] Input과 Output을 ViewModel에 구현
- [ ] ViewModel 이벤트와 VC의 이벤트를 바인딩
- [ ] Firebase의 값변화를 ViewModel이 listen하도록 구현
- [ ] listen후 값전달, ViewModel이 해당 값을 VC에 전달
