### ISSUE TITLE
[FEAT]: 서버와 연결된 채팅에서 필요한 로직 추가

### ISSUE THREAD

**Issue by yudonlee** [DeveloperAcademy-POSTECH/MacC-Team-Vegeting#120]
## 💡 Issue

- #106 4번 Task
해당 Task는 이전에 프로필인지 아닌지에 따라서 CollectionViewCell을 다르게 나타냈습니다.    
그전에는 임의로 데이터를 입력했던 것과 달리 이제는 메세지를 보낸 사람이 나인지, 다른 사람인지를 [Message]에서 판단합니다. 
### 나, 다른사람이 보낸 메시지, 다른사람 보낸 메시지 + 프로필 세가지 SenderType 판단 로직 구현도
```swift
enum SenderType: CaseIterable {
    case mine
    case other
    case otherNeedProfile
}
```
<img width="336" alt="image" src="https://user-images.githubusercontent.com/39371835/201532709-ba24228d-fb04-4e4e-a45c-ddf775698c7c.png">

### 진행될 작업 스크린샷
| 이전작업 | 추가될 작업 |
| ---------- | ---------- |
| <img width="402" alt="image" src="https://user-images.githubusercontent.com/39371835/201532132-d6dd8df7-63c8-420d-80ae-fa14b011f48e.png"> | <img width="601" alt="image" src="https://user-images.githubusercontent.com/39371835/201512569-ca32c344-d597-4555-905d-f3e2f6f4e33f.png"> |

## 📝  todo
- [x] 서버로부터 받아온 [message]를 map을 통해 새로운 ViewModel structure 생성
- [x] 새로운 structure array를 ChatRoomViewController와 연결
- [x] ChatRoomVC에서 CollectionViewCell 판단해서 cell 생성
