### ISSUE TITLE
[FEAT]: 프로필 설정 페이지 중 채식 단계를 선택하고 한 줄 소개를 작성하는 페이지를 구현합니다.

### ISSUE THREAD

**Issue by wonhui-kim** [DeveloperAcademy-POSTECH/MacC-Team-Vegeting#136]
## 💡 Issue

프로필 설정 중 4번째 페이지인 채식 단계를 선택, 한줄 소개를 작성하는 페이지를 구현합니다.

## 📝  todo
- [x] tableView로 채식 단계 선택 뷰 구현
- [x] textField로 한 줄 소개 작성 뷰 구현
- [x] ui layout 배치

## 참고한 코드 출처
- []()
