### ISSUE TITLE
[FEAT]: 채팅방의 보조 기능을 구현합니다.(해당 메세지 바로 위에 날짜 표시, 메세지 들어올 때 최하단으로 이동)

### ISSUE THREAD

**Issue by yudonlee** [DeveloperAcademy-POSTECH/MacC-Team-Vegeting#140]
## 💡 Issue

- #106 7번, 8번, 9번 날짜로직

### #106 8번 날짜 로직 및 UI변경
채팅방에서 해당 메세지가 해당 날짜에 가장 먼저 보낸 메세지라 날짜를 표시해야 하는 경우 
- supplementaryView를 통해서 메세지 cell의 item에 날짜를 표시하려고 했음
-------- 
__불가능한 이유__
1. SupplementaryView의 위치 
- supplementaryView가 cell item에서 표시될 때는 다음과 같은 위치입니다.
- https://docs-assets.developer.apple.com/published/67ac13ba03/ns-collection-layout-anchor@2x.png
2. SupplementaryView의 resizing 불가 
- supplementaryView는 cell item내에 존재하는 것으로 parent item 사이즈를 키워줄 수 없음
- Ask To Apple의 apple engineer의 대답입니다 
>supplementary items attached to NSCollectionLayoutGroup and NSCollectionLayoutItem will not “expand” their parent item to create space."
-----
__결론__

따라서 cell내부에 표시되는 supplementaryView는 cell의 사이즈를 resizing하는 것도 불가능하기 때문에 cell내부에서 content들을 가려서 사용할 수 없습니다. 
- 따라서 날짜를 표시해주는 별도의 Cell을 하나 더 만들 예정입니다.
- 기존의 SenderType이라는 enum또한 MessageType으로 rename 될 예정입니다. 
## 📝  todo
- [x] enum messageType 신설
- [x] 키보드가 올라올 때 collectionView도 keyboard 사이즈만큼 스크롤 업
- [x] 메세지가 새로 전송될 때마다 CollectionView scroll을 bottom으로 이동 
- [x] 해당 메세지가 그날의 최신 메세지인지 판단
- [x] 최신 메세지라면 날짜cell을 삽입
