### ISSUE TITLE
[FEAT]: 모임 게시글 상세 뷰를 구현합니다.

### ISSUE THREAD

**Issue by wonhui-kim** [DeveloperAcademy-POSTECH/MacC-Team-Vegeting#19]
## 💡 Issue
모임 게시글의 상세 뷰를 구현합니다.
<img src="https://user-images.githubusercontent.com/96123303/197369880-6145fc24-c881-4f54-b7f0-6cb644abbb07.png" width=200>

## 📝  todo
- [x] ImageView로 배경 사진
- [x] UILabel로 제목 및 내용
- [x] horizontal collectionView로 참여자들 프로필
- [x] UIButton으로 참여하기 버튼
- [x] half modal로 채팅방 입장 확인

## 참고한 코드 출처
- []()
