### ISSUE TITLE
[TESTFLIGHT]: 마감 기준, 최신순 정렬, 겹치는 에러 

### ISSUE THREAD

**Issue by kelly1422** [DeveloperAcademy-POSTECH/MacC-Team-Vegeting#205]
## 💡 Issue
마감 기준 수정
참여한 모임, 마감 모임 소팅
최신순 정렬 필요
메인뷰 제목 글자수 넘어가면 겹쳐보이는 에러 해결

## 📝  todo
- [ ] 마감 기준 수정
- [ ] 참여한 모임, 마감 모임 소팅
- [ ] 최신순 정렬 필요
- [ ] 메인뷰 제목 글자수 넘어가면 겹쳐보이는 에러 해결

## 참고한 코드 출처
- []()
