### ISSUE TITLE
[FEAT]: PostDetailView 내부 textLabel 배치

### ISSUE THREAD

**Issue by wonhui-kim** [DeveloperAcademy-POSTECH/MacC-Team-Vegeting#31]
## 💡 Issue
PostDetailView 내부 textLabel을 생성, 배치합니다.

## 📝  todo
- [ ] title textLabel 생성, 배치
- [ ] category textLabel 생성, 배치
- [ ] location textLabel 생성, 배치
- [ ] date textLabel 생성, 배치
- [ ] 인원 capacity textLabel 생성, 배치
- [ ] content textLabel 생성, 배치

## 참고한 코드 출처
- [UILabel 스택뷰로 구현](https://velog.io/@sun02/UIStackView-코드로-작성하기)
- [스택뷰 autolayout](https://babbab2.tistory.com/154?category=932180)
