### ISSUE TITLE
[FEAT]: Firebase 채팅 Collection 추가 및 채팅 전송 

### ISSUE THREAD

**Issue by yudonlee** [DeveloperAcademy-POSTECH/MacC-Team-Vegeting#48]
## 💡 Issue

1. Firebase 채팅 기능을 위한 서버 전송 함수
2. Firebase 모임생성 -> 채팅생성 플로우 구현
## 📝  todo
- [ ] Firebase 채팅 생성
- [ ] 채팅 내용 전송
- [ ] 모임생성  <-> 채팅 서로간 DocumentID 공유 하도록 구현

## 참고한 코드 출처
- []()
