### ISSUE TITLE
[FEAT]: Apple Login 구현

### ISSUE THREAD

**Issue by yudonlee** [DeveloperAcademy-POSTECH/MacC-Team-Vegeting#70]
## 💡 Issue

<img src= https://user-images.githubusercontent.com/39371835/201321340-f57fc33b-8758-47ee-9e5d-6afe8c9d769f.png width = 300> 
저희 앱은 카카오 로그인과 애플 로그인을 쓰기로 했고, 파이어베이스의 데이터까지 쓰기 때문에 FirebaseAuth를 통한 계정 로그인 시스템을 구현하기로 했습니다.      
애플 로그인은 FirebaseAuth에서 자체적으로 기능 지원을 해주기 때문에 애플 로그인을 먼저 구현하기로 하였습니다.  

## 📝  todo
- [ ] signInViewModel 생성(애플 로그인의 이벤트 발생을 Input, 결과 Event를 ViewController로 전송)
- [ ] 애플 로그인 구현
- [ ] 애플 로그인시 획득한 Credential, Firebase와 연결하는 로직
