### ISSUE TITLE
[FEAT]: 회원가입 후 유저 프로필 항목 설정

### ISSUE THREAD

**Issue by wonhui-kim** [DeveloperAcademy-POSTECH/MacC-Team-Vegeting#71]
## 💡 Issue

회원가입 이후 프로필 사진, 닉네임, 위치, 성별, 출생 연도 등 개인 정보를 등록하는 화면을 구현합니다.

## 📝  todo
- [ ] photoPicker를 이용한 프로필 사진
- [ ] textField, 닉네임 글자수 제한
- [ ] 필수 항목 입력 후 다음 버튼 활성화
- [ ] 위치 인증
- [ ] 성별 선택 캐러셀
- [ ] 출생년도 picker 이용

## 참고한 코드 출처
- []()
