### ISSUE TITLE
[FEAT]: profile-nickname 입력 뷰 구현

### ISSUE THREAD

**Issue by wonhui-kim** [DeveloperAcademy-POSTECH/MacC-Team-Vegeting#72]
## 💡 Issue

회원 가입 후 프로필 설정 flow 중 프로필, 닉네임 입력 뷰를 구현합니다

## 📝  todo
- [x] photoPicker 이용한 프로필 사진
- [x] 닉네임 입력 (글자 수 제한)
- [x] progress bar
- [x] 필수 항목 모두 입력 후 버튼 활성화

## 참고한 코드 출처
- [textField 밑줄 추가](https://g-y-e-o-m.tistory.com/64)
- [textField 글자수제한](https://velog.io/@sso0022/iOS-TextField-글자수-제한하기-한글)
- [버튼 비활성화](https://dev-geeyong.tistory.com/22)
