### ISSUE TITLE
[FEAT]: SignInWithKakao의 로직을 구현합니다.

### ISSUE THREAD

**Issue by yudonlee** [DeveloperAcademy-POSTECH/MacC-Team-Vegeting#86]
## 💡 Issue

- Apple Sign In까지만 구현된 로그인 기능에 카카오톡 로그인 기능을 완벽하게 구현합니다.
- Kakao Sign In에 Firebase를 연결하기 위해선 사용자에게 이메일을 반드시 요구해야 합니다.
- 관련 Discussion 참고! #85 

## 📝  todo
- [ ] 카카오 앱이 있을 때 로직 구현
- [ ] 카카오 앱이 없을 때 로직 구현
- [ ] 로그인 후 파이어베이스에 로그인
